<?php
/*
AUTHOR:- RITHUNAND [BENCHAMXD]
CHANNEL:- @INDUSBOTS 
THIS REPO IS LICENCED WITH GENERAL PUBLIC LICENSE VERSION:3.0
(c) RITHUNAND K
*/
$TG_BOT_TOKEN = $_ENV['1582636407:AAGuKzkSdzblLiJKqfPbJ9tFeGQKPi7h_PM'];
$BOT_NAME = $_ENV['Bebe'];
$BOT_USERNAME = $_ENV['@Babe_robot'];

?>
